# -----------------------------------------------------------------------------
#  User configuration
# -----------------------------------------------------------------------------

# github pages 호스팅을 사용하는 경우 https://<github사용자 계정>.github.io 세팅
# (커스텀 도메인을 사용할 경우 불필요).
# url:                   https://caias.github.io

# 블로그 루트 폴더 설정
baseurl:               ''

# 블로그 타이틀 설정
title:                 Dev Diary

# 블로그 디스크립션 설정
description:           >
  기억보단 기록을 하고싶은...

# A shorter description for the sidebar.
tagline:               >
  "FrontEnd Dev Diary"

# A list of keywords for your blog
keywords:              []

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/icons/icon.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  name:                LEE KANGWON
  email:               <caias1018@gmail.com>
  # Used by `jekyll-seo-tag`:
  # twitter:             <username>

color:               '#4f86aa'

# Add links to the sidebar.
# menu:
#   - title:             About
#     url:               /about/
#   - title:             FrontEnd
#     url:               /frontend/
#   - title:             Dev Log
#     url:               /devlog/
#   - title:             UI Dev
#     url:               /ui/

# Add links to the footer.
# Typically you'll want to link to your cookie- or privacy policy (if appliable), etc..
# legal:
#   - title:             Impress
#     url:               /impress/
#   - title:             Cookies Policy
#     url:               /cookies-policy/

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2019. All rights reserved. - by caias.

# Format of the permalinks
permalink:             pretty

# Pagination configuration (used by the `blog` layout)
paginate:              8
paginate_path:         /page-:num/

# The font used for headings. Expects a string that is a valid CSS font-family value.
font_heading:        Lato

# The text font. Expects a string that is a valid CSS font-family value.
font:                Lato

# The string encoding what fonts to fetch from Google Fonts.
# See: https://qwtel.com/hydejack/docs/configuration/
google_fonts:        Lato


# 3rd Party Integrations
# ----------------------------------------------------------------------------------------

# Set your Google Analytics id to receive `pageview` events.
# To remove Google Anaylics from your page, remove the line below.
google_analytics:      UA-141774681-1

# Setting a disqus shortname will enable the comment section on
# pages with `comments: true` in the front matter.
disqus:                caias-blog

# Collections
# ========================================================================================

collections:
  featured_categories:
    permalink:         /:name/
    output:            true

  # featured_tags:
  #   permalink:         /tag-:name/
  #   output:            true

  # projects:
  #   permalink:         /projects/:path/
  #   output:            true


# File inclusion/exclusion
# ========================================================================================

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - "*.gemspec"
  - _js
  - _plugins
  - .sass-cache
include:
  - LICENSE.md


# Plugins
# ========================================================================================

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# SEO Tag
# ---------------------------------------------------------------------------------------

# Where you proof that you own this site (used by jekyll-seo-tag)
# google_site_verification: <verification-id>
# -- or --
# webmaster_verifications:
#   google:              <verification-id>
#   bing:                <verification-id>
#   alexa:               <verification-id>
#   yandex:              <verification-id>

# Used for Twitter cards
# twitter:
#   username:            <shortname>

# Used for Facebook open graph
# facebook:
#   app_id:              <id>
#   publisher:           <id>
#   admins:              <id>

# Used on index and about sites
# social:
#   name:                <firstname> <lastname>
#   links:
#     - https://twitter.com/<username>
#     - https://github.com/<username>

github_username:  caias
codepen_username: caias

highlighter:           rouge

# Other Plugins
# ---------------------------------------------------------------------------------------

kramdown:
  footnote_backlink:   '&#x21a9;&#xfe0e;'
  math_engine:         mathjax
  math_engine_opts:
    preview:           true
    preview_as_code:   true

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed
